name: tests

on:
    push:
        branches:
            - main

    pull_request:

permissions:
    contents: read

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v7
              with:
                  persist-credentials: false

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.5"
                  tools: composer:v2
                  coverage: none

            - name: Setup Node
              uses: actions/setup-node@v7
              with:
                  node-version: "22"
                  cache: npm

            - name: Verify PHP
              run: |
                  php -v
                  composer --version

            - name: Setup Application
              run: composer setup

            - name: Run CI Checks
              run: composer ci:check
